native rp_jail_vipjail(Player,Client);
native rp_jail_suicidechamber(Player,Client);
native rp_jail_autoFreeTimerKill(Client);
native rp_jail_autofree(Player, Time);
native rp_jail_jailtimer(Player);
native rp_jail(Client, Combine);
native rp_jail_getAutoFree(Client);
native rp_jail_setAutoFree(Client, Amount);

native rp_jail_getTimeinJail(Client);
native rp_jail_setTimeinJail(Client, Amount);

